server:
  port: 6040
  servlet:
    # default
    context-path: /
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

spring:
  profiles:
    include:
      - oauth
  datasource:
    url: jdbc:mysql://localhost:5281/shopdb?characterEncoding=utf8&ServerTimezone=UTC
#    username: shop
#    password: shopdbdb24.
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: user
      password: password

#  mustache:
#    prefix: classpath:/templates/
#    suffix: .mustache

#mybatis:
#  config-location: classpath*:mapper/mybatis-config.xml
#  mapper-locations: classpath*:mapper/**/*.xml
#  type-aliases-package: com.shop.market.dto
#  configuration:
#    map-underscore-to-camel-case: true